# Site settings
title: Pedro M. Duarte
email: pmd323@gmail.com
description: "My website."
baseurl: ""
url: "http://pedromduarte.github.io"
twitter_username: pmd323
github_username:  pedromduarte

# Build settings
markdown: kramdown
permalink: pretty
